#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

md5sum --check \
       --quiet \
       --ignore-missing \
       ./hashes || exit 1

DOCKER_BUILDKIT=1 docker build --network host -t q2ded:latest .
