#!/usr/bin/env bash
set -euo pipefail

cd $(dirname $0)/..

md5sum --check --quiet data/free/hashes || exit 1

if which docker 2>/dev/null; then
  cmd="docker"
else
  cmd="podman"
fi

${cmd} build --network host -t quake2_server:latest .
