#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)" || exit

md5sum --check \
       --quiet \
       --ignore-missing \
       ./hashes || exit 1

DOCKER_BUILDKIT=1 docker build --file Dockerfile.yquake2 \
                               --network host \
                               --tag q2ded:yquake2 \
                               .
